---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  labels:
    app: service
  annotations:
    fluxcd.io/automated: "true"
spec:
  ports:
  - port: 5432
  selector:
    app: service
    tier: pgsql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  labels:
    app: service
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: service
      tier: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service
        tier: pgsql
    spec:
      containers:
      - image: postgres:13-alpine
        name: pgsql
        env:
        - name: POSTGRES_DB
          value: sample
        - name: POSTGRES_USER
          value: sample
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-pass-ft52m764hb
              key: password
        ports:
        - containerPort: 5432
          name: pgsql
        volumeMounts:
        - name: pgsql-persistent-storage
          mountPath: /var/lib/pgsql
      volumes:
      - name: pgsql-persistent-storage
        persistentVolumeClaim:
          claimName: pgsql-pv-claim
