apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv
  labels:
    app: service
    type: local
  annotations:
    fluxcd.io/automated: "true"
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pv-claim
  labels:
    app: service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
